"""
AIRS-Bench task configuration registry.

Single source of truth for all 20 tasks: names, metrics, dataset info,
scoring columns, submission formats, and SOTA values.

Derived from the original metadata.yaml files in the AIRS-Bench repo.
"""

from dataclasses import dataclass, field


@dataclass
class TaskConfig:
    """Configuration for a single AIRS-Bench task."""
    name: str
    metric: str
    lower_is_better: bool
    dataset: str
    dataset_config: str
    scoring_column: str
    train_split: str
    test_split: str
    category: str
    research_problem: str
    # Columns to remove from test set (the agent shouldn't see these)
    columns_to_remove: list[str] = field(default_factory=list)
    # For tasks with custom_gold_labels, evaluation is more complex
    custom_gold_labels: bool = False
    # SOTA reference values
    sota_score: float | None = None
    estimated_worst_score: float = 0.0
    optimal_score: float = 1.0
    # Submission format hints
    submission_columns: list[str] = field(default_factory=lambda: ["prediction"])


TASKS: dict[str, TaskConfig] = {
    "MathQuestionAnsweringSVAMPAccuracy": TaskConfig(
        name="MathQuestionAnsweringSVAMPAccuracy",
        metric="Accuracy",
        lower_is_better=False,
        dataset="ChilleD/SVAMP",
        dataset_config="default",
        scoring_column="Answer",
        train_split="train",
        test_split="test",
        category="Math",
        research_problem="Math Question Answering",
        columns_to_remove=["Equation", "Answer", "Type"],
        custom_gold_labels=False,
        sota_score=0.942,
        estimated_worst_score=0.0,
        optimal_score=1.0,
        submission_columns=["Answer"],
    ),
    "CoreferenceResolutionWinograndeAccuracy": TaskConfig(
        name="CoreferenceResolutionWinograndeAccuracy",
        metric="Accuracy",
        lower_is_better=False,
        dataset="allenai/winogrande",
        dataset_config="winogrande_xl",
        scoring_column="answer",
        train_split="train",
        test_split="validation",
        category="NLP",
        research_problem="Coreference Resolution",
        columns_to_remove=["answer"],
        custom_gold_labels=False,
        sota_score=0.904,
        estimated_worst_score=0.4664562,
        optimal_score=1.0,
        submission_columns=["answer"],
    ),
    "CoreferenceResolutionSuperGLUEWSCAccuracy": TaskConfig(
        name="CoreferenceResolutionSuperGLUEWSCAccuracy",
        metric="Accuracy",
        lower_is_better=False,
        dataset="aps/super_glue",
        dataset_config="wsc",
        scoring_column="label",
        train_split="train",
        test_split="validation",
        category="NLP",
        research_problem="Coreference Resolution",
        columns_to_remove=["label"],
        custom_gold_labels=False,
        sota_score=0.962,
        estimated_worst_score=0.3653846154,
        optimal_score=1.0,
        submission_columns=["label"],
    ),
    "SentimentAnalysisYelpReviewFullAccuracy": TaskConfig(
        name="SentimentAnalysisYelpReviewFullAccuracy",
        metric="Accuracy",
        lower_is_better=False,
        dataset="Yelp/yelp_review_full",
        dataset_config="yelp_review_full",
        scoring_column="label",
        train_split="train",
        test_split="test",
        category="NLP",
        research_problem="Sentiment Analysis",
        columns_to_remove=["label"],
        custom_gold_labels=False,
        sota_score=0.7280,
        estimated_worst_score=0.18208,
        optimal_score=1.0,
        submission_columns=["label"],
    ),
    "TextualClassificationSickAccuracy": TaskConfig(
        name="TextualClassificationSickAccuracy",
        metric="Accuracy",
        lower_is_better=False,
        dataset="RobZamp/sick",
        dataset_config="default",
        scoring_column="label",
        train_split="train",
        test_split="test",
        category="NLP",
        research_problem="Textual Classification",
        columns_to_remove=["label"],
        custom_gold_labels=False,
        sota_score=0.9370,
        estimated_worst_score=0.1451284,
        optimal_score=1.0,
        submission_columns=["label"],
    ),
    "QuestionAnsweringFinqaAccuracy": TaskConfig(
        name="QuestionAnsweringFinqaAccuracy",
        metric="FinQAAccuracy",
        lower_is_better=False,
        dataset="dreamerdeo/finqa",
        dataset_config="default",
        scoring_column="answer",
        train_split="train",
        test_split="test",
        category="NLP",
        research_problem="Question Answering",
        columns_to_remove=["answer"],
        custom_gold_labels=False,
        sota_score=0.680,
        estimated_worst_score=0.0,
        optimal_score=1.0,
        submission_columns=["answer"],
    ),
    "QuestionAnsweringDuoRCAccuracy": TaskConfig(
        name="QuestionAnsweringDuoRCAccuracy",
        metric="DuoRCAccuracy",
        lower_is_better=False,
        dataset="ibm-research/duorc",
        dataset_config="ParaphraseRC",
        scoring_column="answers",
        train_split="train",
        test_split="test",
        category="NLP",
        research_problem="Question Answering",
        columns_to_remove=["answers", "no_answer"],
        custom_gold_labels=True,
        sota_score=0.696,
        estimated_worst_score=0.0,
        optimal_score=1.0,
        submission_columns=["answer", "has_answer"],
    ),
    "ReadingComprehensionSquadExactMatch": TaskConfig(
        name="ReadingComprehensionSquadExactMatch",
        metric="ExactMatch",
        lower_is_better=False,
        dataset="rajpurkar/squad",
        dataset_config="plain_text",
        scoring_column="answers",
        train_split="train",
        test_split="validation",
        category="NLP",
        research_problem="Reading Comprehension",
        columns_to_remove=["answers"],
        custom_gold_labels=True,
        sota_score=0.900,
        estimated_worst_score=0.0,
        optimal_score=1.0,
        submission_columns=["answers"],
    ),
    "QuestionAnsweringEli5Rouge1": TaskConfig(
        name="QuestionAnsweringEli5Rouge1",
        metric="Rouge1",
        lower_is_better=False,
        dataset="Pavithree/eli5",
        dataset_config="default",
        scoring_column="answers",
        train_split="train",
        test_split="test",
        category="NLP",
        research_problem="Question Answering",
        columns_to_remove=["answers"],
        custom_gold_labels=True,
        sota_score=0.290,
        estimated_worst_score=0.002451528,
        optimal_score=1.0,
        submission_columns=["answers"],
    ),
    "TextualSimilaritySickSpearmanCorrelation": TaskConfig(
        name="TextualSimilaritySickSpearmanCorrelation",
        metric="SpearmanCorrelation",
        lower_is_better=False,
        dataset="RobZamp/sick",
        dataset_config="default",
        scoring_column="relatedness_score",
        train_split="train",
        test_split="test",
        category="NLP",
        research_problem="Textual Similarity",
        columns_to_remove=["relatedness_score"],
        custom_gold_labels=False,
        sota_score=0.900,
        estimated_worst_score=-0.5870786,
        optimal_score=1.0,
        submission_columns=["relatedness_score"],
    ),
    "CodeRetrievalCodeXGlueMRR": TaskConfig(
        name="CodeRetrievalCodeXGlueMRR",
        metric="MRR",
        lower_is_better=False,
        dataset="google/code_x_glue_tc_nl_code_search_adv",
        dataset_config="default",
        scoring_column="id",
        train_split="train",
        test_split="test",
        category="Code",
        research_problem="Code Retrieval",
        columns_to_remove=[],  # id is needed for both query and label
        custom_gold_labels=True,
        sota_score=0.395,
        estimated_worst_score=0.0,
        optimal_score=1.0,
        submission_columns=["query", "rankings"],
    ),
    "CodeGenerationAPPSPassAt5": TaskConfig(
        name="CodeGenerationAPPSPassAt5",
        metric="Pass@5",
        lower_is_better=False,
        dataset="codeparrot/apps",
        dataset_config="all",
        scoring_column="input_output",
        train_split="train",
        test_split="test",
        category="Code",
        research_problem="Code Generation",
        columns_to_remove=["input_output", "solutions"],
        custom_gold_labels=True,
        sota_score=0.187,
        estimated_worst_score=0.0,
        optimal_score=1.0,
        submission_columns=["code1", "code2", "code3", "code4", "code5"],
    ),
    "CvMolecularPropertyPredictionQm9MeanAbsoluteError": TaskConfig(
        name="CvMolecularPropertyPredictionQm9MeanAbsoluteError",
        metric="MAE",
        lower_is_better=True,
        dataset="nimashoghi/qm9",
        dataset_config="default",
        scoring_column="c_v",
        train_split="train",
        test_split="test",
        category="Molecules",
        research_problem="Molecular Property Prediction",
        columns_to_remove=["c_v"],
        custom_gold_labels=False,
        sota_score=0.012,
        estimated_worst_score=132.63319396972656,
        optimal_score=0.0,
        submission_columns=["c_v"],
    ),
    "GMolecularPropertyPredictionQm9MeanAbsoluteError": TaskConfig(
        name="GMolecularPropertyPredictionQm9MeanAbsoluteError",
        metric="MAE",
        lower_is_better=True,
        dataset="nimashoghi/qm9",
        dataset_config="default",
        scoring_column="G",
        train_split="train",
        test_split="test",
        category="Molecules",
        research_problem="Molecular Property Prediction",
        columns_to_remove=["G"],
        custom_gold_labels=True,
        sota_score=0.008,
        estimated_worst_score=11185110,
        optimal_score=0.0,
        submission_columns=["G"],
    ),
    "R2AbsMolecularPropertyPredictionQm9MeanAbsoluteError": TaskConfig(
        name="R2AbsMolecularPropertyPredictionQm9MeanAbsoluteError",
        metric="MAE",
        lower_is_better=True,
        dataset="nimashoghi/qm9",
        dataset_config="default",
        scoring_column="R_2_Abs",
        train_split="train",
        test_split="test",
        category="Molecules",
        research_problem="Molecular Property Prediction",
        columns_to_remove=["R_2_Abs"],
        custom_gold_labels=False,
        sota_score=0.010,
        estimated_worst_score=6536.567,
        optimal_score=0.0,
        submission_columns=["R_2_Abs"],
    ),
    "U0MolecularPropertyPredictionQm9MeanAbsoluteError": TaskConfig(
        name="U0MolecularPropertyPredictionQm9MeanAbsoluteError",
        metric="MAE",
        lower_is_better=True,
        dataset="nimashoghi/qm9",
        dataset_config="default",
        scoring_column="U_0",
        train_split="train",
        test_split="test",
        category="Molecules",
        research_problem="Molecular Property Prediction",
        columns_to_remove=["U_0"],
        custom_gold_labels=True,
        sota_score=0.005,
        estimated_worst_score=24183970,
        optimal_score=0.0,
        submission_columns=["U_0"],
    ),
    "GraphRegressionZincMae": TaskConfig(
        name="GraphRegressionZincMae",
        metric="MAE",
        lower_is_better=True,
        dataset="graphs-datasets/ZINC",
        dataset_config="default",
        scoring_column="y",
        train_split="train",
        test_split="test",
        category="Graph",
        research_problem="Graph Regression",
        columns_to_remove=["y"],
        custom_gold_labels=False,
        sota_score=0.059,
        estimated_worst_score=9.699924,
        optimal_score=0.0,
        submission_columns=["y"],
    ),
    "TimeSeriesForecastingKaggleWebTrafficMASE": TaskConfig(
        name="TimeSeriesForecastingKaggleWebTrafficMASE",
        metric="MASE",
        lower_is_better=True,
        dataset="Monash-University/monash_tsf",
        dataset_config="kaggle_web_traffic",
        scoring_column="",  # complex time series format
        train_split="train",
        test_split="test",
        category="TimeSeries",
        research_problem="Time Series Forecasting",
        columns_to_remove=[],
        custom_gold_labels=True,
        sota_score=0.700,
        estimated_worst_score=502962963078372,
        optimal_score=0.0,
        submission_columns=["prediction"],
    ),
    "TimeSeriesForecastingRideshareMAE": TaskConfig(
        name="TimeSeriesForecastingRideshareMAE",
        metric="TimeSeriesMAE",
        lower_is_better=True,
        dataset="Monash-University/monash_tsf",
        dataset_config="rideshare",
        scoring_column="",
        train_split="train",
        test_split="test",
        category="TimeSeries",
        research_problem="Time Series Forecasting",
        columns_to_remove=[],
        custom_gold_labels=True,
        sota_score=2.450,
        estimated_worst_score=30.22490,
        optimal_score=0.0,
        submission_columns=["prediction"],
    ),
    "TimeSeriesForecastingSolarWeeklyMAE": TaskConfig(
        name="TimeSeriesForecastingSolarWeeklyMAE",
        metric="TimeSeriesMAE",
        lower_is_better=True,
        dataset="Monash-University/monash_tsf",
        dataset_config="solar_weekly",
        scoring_column="",
        train_split="train",
        test_split="test",
        category="TimeSeries",
        research_problem="Time Series Forecasting",
        columns_to_remove=[],
        custom_gold_labels=True,
        sota_score=200.0,
        estimated_worst_score=34761.99,
        optimal_score=0.0,
        submission_columns=["prediction"],
    ),
}

# All task names in stable sorted order
TASK_NAMES = sorted(TASKS.keys())
